time: 2014-01-06 12:26:22.364424Z
tags: worker-0
test: tempest.scenario.test_volume_boot_pattern.TestVolumeBootPattern.test_volume_boot_pattern[compute,image,volume]
time: 2014-01-06 12:32:05.914384Z
failure: tempest.scenario.test_volume_boot_pattern.TestVolumeBootPattern.test_volume_boot_pattern[compute,image,volume] [ multipart
Content-Type: text/plain;charset="utf8"
pythonlogging:''
0
Content-Type: text/plain;charset="utf8"
stderr
0
Content-Type: text/plain;charset="utf8"
stdout
0
Content-Type: text/x-traceback;charset="utf8",language="python"
traceback
EB
Traceback (most recent call last):
  File "/home/os1/tempest/tempest/scenario/test_volume_boot_pattern.py", line 220, in test_volume_boot_pattern
    keypair)
TypeError: _boot_instance_from_volume() takes exactly 4 arguments (3 given)
0
]
tags: -worker-0
time: 2014-01-06 12:32:35.098882Z
tags: worker-0
test: process-returncode
time: 2014-01-06 12:32:35.098882Z
failure: process-returncode [ multipart
Content-Type: test/plain;charset=utf8
traceback
C
returncode 10
]
tags: -worker-0
