time: 2014-01-06 21:30:43.314490Z
tags: worker-0
test: setUpClass (tempest.scenario.test_minimum_basic.TestMinimumBasicScenario)
time: 2014-01-06 21:30:43.314490Z
failure: setUpClass (tempest.scenario.test_minimum_basic.TestMinimumBasicScenario) [ multipart
Content-Type: text/x-traceback;charset="utf8",language="python"
traceback
526
Traceback (most recent call last):
  File "/home/os1/tempest/tempest/scenario/test_minimum_basic.py", line 52, in setUpClass
    super(TestMinimumBasicScenario, cls).setUpClass()
  File "/home/os1/tempest/tempest/scenario/manager.py", line 500, in setUpClass
    super(NetworkScenarioTest, cls).setUpClass()
  File "/home/os1/tempest/tempest/scenario/manager.py", line 209, in setUpClass
    __name__, tempest_client=False)
  File "/home/os1/tempest/tempest/common/isolated_creds.py", line 44, in __init__
    self._get_admin_clients())
  File "/home/os1/tempest/tempest/common/isolated_creds.py", line 76, in _get_admin_clients
    admin_clients = self._get_official_admin_clients()
  File "/home/os1/tempest/tempest/common/isolated_creds.py", line 56, in _get_official_admin_clients
    insecure=dscv)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v2_0/client.py", line 139, in __init__
    self.authenticate()
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 468, in authenticate
    resp, body = self.get_raw_token_from_identity_service(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v2_0/client.py", line 168, in get_raw_token_from_identity_service
    "%s" % e)
AuthorizationFailure: Authorization Failed: Service Unavailable (HTTP 503)
0
]
tags: -worker-0
time: 2014-01-06 21:30:43.366661Z
tags: worker-0
test: process-returncode
time: 2014-01-06 21:30:43.366661Z
failure: process-returncode [ multipart
Content-Type: test/plain;charset=utf8
traceback
C
returncode 10
]
tags: -worker-0
