time: 2014-01-09 10:50:03.356514Z
tags: worker-0
test: tempest.scenario.test_network_quotas.TestNetworkQuotaBasic.test_create_network_until_quota_hit[network]
time: 2014-01-09 10:50:04.650054Z
successful: tempest.scenario.test_network_quotas.TestNetworkQuotaBasic.test_create_network_until_quota_hit[network] [ multipart
Content-Type: text/plain;charset="utf8"
pythonlogging:''
0
Content-Type: text/plain;charset="utf8"
stderr
0
Content-Type: text/plain;charset="utf8"
stdout
0
]
tags: -worker-0
time: 2014-01-09 10:50:04.651737Z
tags: worker-0
test: tempest.scenario.test_network_quotas.TestNetworkQuotaBasic.test_create_ports_until_quota_hit[network]
time: 2014-01-09 10:50:25.946112Z
successful: tempest.scenario.test_network_quotas.TestNetworkQuotaBasic.test_create_ports_until_quota_hit[network] [ multipart
Content-Type: text/plain;charset="utf8"
pythonlogging:''
0
Content-Type: text/plain;charset="utf8"
stderr
0
Content-Type: text/plain;charset="utf8"
stdout
0
]
tags: -worker-0
time: 2014-01-09 10:50:25.947640Z
tags: worker-0
test: tempest.scenario.test_network_quotas.TestNetworkQuotaBasic.test_create_subnet_until_quota_hit[network]
time: 2014-01-09 10:50:44.463032Z
successful: tempest.scenario.test_network_quotas.TestNetworkQuotaBasic.test_create_subnet_until_quota_hit[network] [ multipart
Content-Type: text/plain;charset="utf8"
pythonlogging:''
0
Content-Type: text/plain;charset="utf8"
stderr
0
Content-Type: text/plain;charset="utf8"
stdout
0
]
tags: -worker-0
time: 2014-01-09 10:51:13.390697Z
tags: worker-0
test: tearDownClass (tempest.scenario.test_network_quotas.TestNetworkQuotaBasic)
time: 2014-01-09 10:51:13.390697Z
failure: tearDownClass (tempest.scenario.test_network_quotas.TestNetworkQuotaBasic) [ multipart
Content-Type: text/x-traceback;charset="utf8",language="python"
traceback
66B
Traceback (most recent call last):
  File "/home/os1/tempest/tempest/scenario/manager.py", line 272, in tearDownClass
    cls.isolated_creds.clear_isolated_creds()
  File "/home/os1/tempest/tempest/common/isolated_creds.py", line 457, in clear_isolated_creds
    self._clear_isolated_net_resources()
  File "/home/os1/tempest/tempest/common/isolated_creds.py", line 439, in _clear_isolated_net_resources
    net_client.remove_interface_router(router['id'], body)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 108, in with_params
    ret = self.function(instance, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 410, in remove_interface_router
    "/remove_router_interface", body=body)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 1192, in put
    headers=headers, params=params)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 1168, in retry_request
    headers=headers, params=params)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 1111, in do_request
    self._handle_fault_response(status_code, replybody)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 1081, in _handle_fault_response
    exception_handler_v20(status_code, des_error_body)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 88, in exception_handler_v20
    message=message)
NeutronClientException: <html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

0
]
tags: -worker-0
time: 2014-01-09 10:51:13.457688Z
tags: worker-0
test: process-returncode
time: 2014-01-09 10:51:13.457688Z
failure: process-returncode [ multipart
Content-Type: test/plain;charset=utf8
traceback
C
returncode 10
]
tags: -worker-0
