time: 2014-01-16 20:15:15.994977Z
tags: worker-0
test: tempest.scenario.test_dashboard_basic_ops.TestDashboardBasicOps.test_basic_scenario[dashboard]
time: 2014-01-16 20:15:16.344897Z
failure: tempest.scenario.test_dashboard_basic_ops.TestDashboardBasicOps.test_basic_scenario[dashboard] [ multipart
Content-Type: text/plain;charset="utf8"
pythonlogging:''
0
Content-Type: text/plain;charset="utf8"
stderr
0
Content-Type: text/plain;charset="utf8"
stdout
0
Content-Type: text/x-traceback;charset="utf8",language="python"
traceback
3F7
Traceback (most recent call last):
  File "/home/os1/tempest/tempest/scenario/test_dashboard_basic_ops.py", line 72, in test_basic_scenario
    self.check_login_page()
  File "/home/os1/tempest/tempest/scenario/test_dashboard_basic_ops.py", line 43, in check_login_page
    response = urllib2.urlopen(self.config.dashboard.dashboard_url)
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
0
]
tags: -worker-0
time: 2014-01-16 20:15:17.089120Z
tags: worker-0
test: process-returncode
time: 2014-01-16 20:15:17.089120Z
failure: process-returncode [ multipart
Content-Type: test/plain;charset=utf8
traceback
C
returncode 10
]
tags: -worker-0
