time: 2013-12-20 11:29:24.686486Z
tags: worker-0
test: tempest.scenario.test_volume_boot_pattern.TestVolumeBootPattern.test_volume_boot_pattern[compute,image,volume]
time: 2013-12-20 11:31:23.492809Z
successful: tempest.scenario.test_volume_boot_pattern.TestVolumeBootPattern.test_volume_boot_pattern[compute,image,volume] [ multipart
Content-Type: text/plain;charset="utf8"
pythonlogging:''
0
Content-Type: text/plain;charset="utf8"
stderr
0
Content-Type: text/plain;charset="utf8"
stdout
0
]
tags: -worker-0
time: 2013-12-20 11:31:23.609158Z
tags: worker-0
test: tearDownClass (tempest.scenario.test_volume_boot_pattern.TestVolumeBootPattern)
time: 2013-12-20 11:31:23.609158Z
failure: tearDownClass (tempest.scenario.test_volume_boot_pattern.TestVolumeBootPattern) [ multipart
Content-Type: text/x-traceback;charset="utf8",language="python"
traceback
599
Traceback (most recent call last):
  File "/home/os1/tempest/tempest/scenario/manager.py", line 248, in tearDownClass
    thing.delete()
  File "/home/os1/tempest/tempest/api/network/common.py", line 90, in delete
    self.client.delete_floatingip(self.id)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 108, in with_params
    ret = self.function(instance, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 449, in delete_floatingip
    return self.delete(self.floatingip_path % (floatingip))
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 1179, in delete
    headers=headers, params=params)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 1168, in retry_request
    headers=headers, params=params)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 1111, in do_request
    self._handle_fault_response(status_code, replybody)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 1081, in _handle_fault_response
    exception_handler_v20(status_code, des_error_body)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 93, in exception_handler_v20
    message=msg)
NeutronClientException: 404-{u'QuantumError': u'Floating IP 3ecee32a-02f0-4ac5-addb-202ded957864 could not be found'}
0
]
tags: -worker-0
time: 2013-12-20 11:31:23.661042Z
tags: worker-0
test: process-returncode
time: 2013-12-20 11:31:23.661042Z
failure: process-returncode [ multipart
Content-Type: test/plain;charset=utf8
traceback
C
returncode 10
]
tags: -worker-0
