time: 2014-01-21 15:37:14.684312Z
tags: worker-0
test: tempest.scenario.test_minimum_basic.TestMinimumBasicScenario.test_minimum_basic_scenario[compute,image,network,volume]
time: 2014-01-21 15:45:35.199881Z
failure: tempest.scenario.test_minimum_basic.TestMinimumBasicScenario.test_minimum_basic_scenario[compute,image,network,volume] [ multipart
Content-Type: text/plain;charset="utf8"
pythonlogging:''
0
Content-Type: text/plain;charset="utf8"
stderr
0
Content-Type: text/plain;charset="utf8"
stdout
0
Content-Type: text/x-traceback;charset="utf8",language="python"
traceback
3CF
Traceback (most recent call last):
  File "/home/os1/tempest/tempest/scenario/test_minimum_basic.py", line 176, in test_minimum_basic_scenario
    self.nova_volume_attach()
  File "/home/os1/tempest/tempest/scenario/test_minimum_basic.py", line 131, in nova_volume_attach
    self._wait_for_volume_status('in-use')
  File "/home/os1/tempest/tempest/scenario/test_minimum_basic.py", line 66, in _wait_for_volume_status
    self.volume_client.volumes, volume_id, status)
  File "/home/os1/tempest/tempest/scenario/manager.py", line 304, in status_timeout
    not_found_exception=not_found_exception)
  File "/home/os1/tempest/tempest/scenario/manager.py", line 358, in _status_timeout
    self.config.compute.build_interval):
  File "/home/os1/tempest/tempest/test.py", line 293, in call_until_true
    time.sleep(sleep_for)
  File "/usr/local/lib/python2.7/dist-packages/fixtures/_fixtures/timeout.py", line 52, in signal_handler
    raise TimeoutException()
TimeoutException
0
]
tags: -worker-0
time: 2014-01-21 15:45:42.664651Z
tags: worker-0
test: process-returncode
time: 2014-01-21 15:45:42.664651Z
failure: process-returncode [ multipart
Content-Type: test/plain;charset=utf8
traceback
C
returncode 10
]
tags: -worker-0
