time: 2013-12-19 16:07:21.080981Z
tags: worker-0
test: tempest.scenario.test_volume_boot_pattern.TestVolumeBootPattern.test_volume_boot_pattern[compute,image,volume]
time: 2013-12-19 16:07:22.169683Z
failure: tempest.scenario.test_volume_boot_pattern.TestVolumeBootPattern.test_volume_boot_pattern[compute,image,volume] [ multipart
Content-Type: text/plain;charset="utf8"
pythonlogging:''
0
Content-Type: text/plain;charset="utf8"
stderr
0
Content-Type: text/plain;charset="utf8"
stdout
0
Content-Type: text/x-traceback;charset="utf8",language="python"
traceback
214
Traceback (most recent call last):
  File "/home/os1/tempest/tempest/scenario/test_volume_boot_pattern.py", line 185, in test_volume_boot_pattern
    volume_origin = self._create_volume_from_image()
  File "/home/os1/tempest/tempest/scenario/test_volume_boot_pattern.py", line 84, in _create_volume_from_image
    img_uuid = self.glance_image_create()
  File "/home/os1/tempest/tempest/scenario/test_volume_boot_pattern.py", line 74, in glance_image_create
    LOG.debug("paths: ami: %s"
NameError: global name 'LOG' is not defined
0
]
tags: -worker-0
